### ISSUE TITLE
Assertion Error occurs when Processing Video Files 

### ISSUE THREAD

**Issue by avrha** [avrha/face_blur#7]
Program crashes and prompts following message:
`Traceback (most recent call last):
  File "face_blur.py", line 21, in <module>
    main()
  File "face_blur.py", line 18, in main
    video(args["input"],args["output"])
  File "/home/avrha/Desktop/face_blur/src/face_detection.py", line 62, in video
    blur_dnn(frame,face)
  File "/home/avrha/Desktop/face_blur/src/blur_filter.py", line 11, in blur_dnn
    box = cv2.GaussianBlur(box,(99,99),30)
cv2.error: OpenCV(4.4.0) /tmp/pip-req-build-qacpj5ci/opencv/modules/imgproc/src/smooth.dispatch.cpp:620: error: (-215:Assertion failed) !_src.empty() in function 'GaussianBlur'
`

**Comment by avrha** [comment]
In commit <386f63a17e118fdb2f7b074431242f36557093f6> I implemented a sloppy fix. The program continues in the for loop if the blur function is executed without error,  and breaks out of the loop if an issue occurs. I'll try to debug this later.

**Comment by avrha** [comment]
Workaround actually fixes the issue
